"""
Seed dataset of 25 real-world food packaging types with plausible LCA (Life Cycle Assessment) values.
Values are grounded in public LCA literature (Ecoinvent, EU PEF studies, industry reports) and are
representative—not for regulatory use. Units:
  co2_kg      : kg CO2-equivalent per packaging unit (cradle-to-grave)
  water_l     : liters of freshwater consumed per unit (cradle-to-gate)
  energy_mj   : megajoules of primary energy per unit (cradle-to-gate)
  recyclability_pct : realistic EU post-consumer recycling rate for material/format
  shelf_life_days   : typical shelf-life the packaging enables for its food category
  cost_eur    : approx. per-unit industrial cost in EUR
  weight_g    : empty packaging weight in grams
  baseline_co2_kg   : reference packaging for its category (used to show % delta)
  score_grade : A (best) to E (worst)
  score_value : 0-100 numeric, higher = greener
"""

PACKAGINGS = [
    {
        "id": "glass-milk-bottle",
        "name": "Returnable Glass Milk Bottle",
        "category": "Dairy",
        "material": "Soda-lime glass",
        "format": "500 ml returnable bottle",
        "image": "https://images.pexels.com/photos/6654106/pexels-photo-6654106.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "co2_kg": 0.09,
        "baseline_co2_kg": 0.12,
        "water_l": 0.9,
        "energy_mj": 2.1,
        "recyclability_pct": 95,
        "shelf_life_days": 7,
        "cost_eur": 0.28,
        "weight_g": 380,
        "score_grade": "A",
        "score_value": 88,
        "highlights": [
            "25 reuse cycles before recycling",
            "Closed-loop EU dairy return scheme",
            "Inert, no microplastic leaching"
        ],
        "lifecycle": [
            {"stage": "Sand & cullet sourcing", "co2_share": 0.18, "note": "70% recycled cullet input"},
            {"stage": "Melting & forming", "co2_share": 0.42, "note": "Gas-fired furnace, 1500°C"},
            {"stage": "Bottling & transport", "co2_share": 0.20, "note": "Regional dairy radius <250km"},
            {"stage": "Use & return", "co2_share": 0.05, "note": "Amortized across 25 reuses"},
            {"stage": "Wash & recycle", "co2_share": 0.15, "note": "Alkaline wash, cullet reclaimed"},
        ],
    },
    {
        "id": "tetra-pak-milk-carton",
        "name": "Aseptic Beverage Carton",
        "category": "Dairy",
        "material": "Paperboard + LDPE + Aluminium (75/20/5)",
        "format": "1 L aseptic carton",
        "image": "https://images.unsplash.com/photo-1698376621029-f5607eee8df7?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzMzV8MHwxfHNlYXJjaHwxfHxjYXJkYm9hcmQlMjBwYWNrYWdpbmclMjBmb29kfGVufDB8fHx8MTc3Njc4ODY3OXww&ixlib=rb-4.1.0&q=85",
        "co2_kg": 0.08,
        "baseline_co2_kg": 0.12,
        "water_l": 1.4,
        "energy_mj": 1.6,
        "recyclability_pct": 51,
        "shelf_life_days": 180,
        "cost_eur": 0.14,
        "weight_g": 28,
        "score_grade": "B",
        "score_value": 74,
        "highlights": [
            "FSC-certified paperboard backbone",
            "6-month ambient shelf life, no refrigeration",
            "Lightweight: 28 g protects 1 kg of product"
        ],
        "lifecycle": [
            {"stage": "Paperboard & aluminium", "co2_share": 0.45, "note": "FSC pulp + thin Al foil"},
            {"stage": "Lamination & forming", "co2_share": 0.20, "note": "Multi-layer bonding"},
            {"stage": "Filling & transport", "co2_share": 0.15, "note": "Stackable, dense pallets"},
            {"stage": "Ambient storage", "co2_share": 0.05, "note": "No cold chain needed"},
            {"stage": "Separation recycling", "co2_share": 0.15, "note": "Hydropulper at paper mill"},
        ],
    },
    {
        "id": "pp-yogurt-cup",
        "name": "Polypropylene Yogurt Cup",
        "category": "Dairy",
        "material": "PP #5 + aluminium foil lid",
        "format": "150 g single-serve cup",
        "image": "https://images.unsplash.com/photo-1619798049475-7fb775c9835c?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2NzV8MHwxfHNlYXJjaHw0fHxzdXN0YWluYWJsZSUyMGZvb2QlMjBwYWNrYWdpbmd8ZW58MHx8fHwxNzc2Nzg4Njc5fDA&ixlib=rb-4.1.0&q=85",
        "co2_kg": 0.036,
        "baseline_co2_kg": 0.035,
        "water_l": 0.3,
        "energy_mj": 0.9,
        "recyclability_pct": 38,
        "shelf_life_days": 35,
        "cost_eur": 0.05,
        "weight_g": 5.2,
        "score_grade": "C",
        "score_value": 55,
        "highlights": [
            "Light (5.2 g) — low transport footprint",
            "PP #5 widely accepted at MRFs",
            "Mixed lid complicates recovery"
        ],
        "lifecycle": [
            {"stage": "Fossil feedstock", "co2_share": 0.55, "note": "Virgin PP resin"},
            {"stage": "Thermoforming", "co2_share": 0.20, "note": "Low-energy forming"},
            {"stage": "Cold-chain transport", "co2_share": 0.15, "note": "4°C storage needed"},
            {"stage": "Consumer use", "co2_share": 0.02, "note": "Short use phase"},
            {"stage": "End-of-life", "co2_share": 0.08, "note": "~38% recycled in EU"},
        ],
    },
    {
        "id": "pet-water-bottle",
        "name": "Virgin PET Water Bottle",
        "category": "Beverages",
        "material": "PET #1 (virgin)",
        "format": "500 ml still water",
        "image": "https://images.unsplash.com/photo-1605545562576-5afc1d2a0c8b?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "co2_kg": 0.083,
        "baseline_co2_kg": 0.12,
        "water_l": 3.4,
        "energy_mj": 1.7,
        "recyclability_pct": 58,
        "shelf_life_days": 730,
        "cost_eur": 0.03,
        "weight_g": 9.9,
        "score_grade": "D",
        "score_value": 42,
        "highlights": [
            "High EU collection rate (DRS schemes)",
            "Lightweight vs. glass (5x less mass)",
            "Relies on virgin fossil feedstock"
        ],
        "lifecycle": [
            {"stage": "Fossil PET resin", "co2_share": 0.62, "note": "Oil-derived, virgin grade"},
            {"stage": "Blow-moulding", "co2_share": 0.18, "note": "Preform + stretch blow"},
            {"stage": "Bulk transport", "co2_share": 0.10, "note": "Long-haul beverage logistics"},
            {"stage": "Use", "co2_share": 0.01, "note": "Minimal"},
            {"stage": "Recycling/landfill", "co2_share": 0.09, "note": "~58% captured via DRS"},
        ],
    },
    {
        "id": "rpet-bottle",
        "name": "100% rPET Bottle",
        "category": "Beverages",
        "material": "Recycled PET #1",
        "format": "500 ml still water",
        "image": "https://images.unsplash.com/photo-1556909114-44e3e70034e2?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "co2_kg": 0.034,
        "baseline_co2_kg": 0.083,
        "water_l": 1.1,
        "energy_mj": 0.8,
        "recyclability_pct": 58,
        "shelf_life_days": 730,
        "cost_eur": 0.05,
        "weight_g": 9.9,
        "score_grade": "B",
        "score_value": 72,
        "highlights": [
            "-59% CO₂ vs virgin PET equivalent",
            "Keeps plastic in circulation",
            "Food-grade rPET supply still tight"
        ],
        "lifecycle": [
            {"stage": "rPET flake sorting", "co2_share": 0.25, "note": "MRF + optical sorting"},
            {"stage": "Decontamination", "co2_share": 0.30, "note": "EFSA food-grade process"},
            {"stage": "Blow-moulding", "co2_share": 0.20, "note": "Same equipment as virgin"},
            {"stage": "Bulk transport", "co2_share": 0.15, "note": "Standard beverage logistics"},
            {"stage": "Recycling loop", "co2_share": 0.10, "note": "Designed for multiple cycles"},
        ],
    },
    {
        "id": "aluminium-can",
        "name": "Aluminium Beverage Can",
        "category": "Beverages",
        "material": "Aluminium (70% recycled)",
        "format": "330 ml can",
        "image": "https://images.unsplash.com/photo-1600275669439-14e40452d20b?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "co2_kg": 0.11,
        "baseline_co2_kg": 0.12,
        "water_l": 1.9,
        "energy_mj": 2.4,
        "recyclability_pct": 76,
        "shelf_life_days": 365,
        "cost_eur": 0.07,
        "weight_g": 14.5,
        "score_grade": "B",
        "score_value": 70,
        "highlights": [
            "Infinitely recyclable without quality loss",
            "76% EU recycling rate",
            "Cold-chain friendly, UV-proof"
        ],
        "lifecycle": [
            {"stage": "Bauxite + recycled Al", "co2_share": 0.50, "note": "70% secondary aluminium"},
            {"stage": "Rolling & forming", "co2_share": 0.25, "note": "Energy intensive step"},
            {"stage": "Transport & filling", "co2_share": 0.12, "note": "Light, stackable"},
            {"stage": "Cold storage", "co2_share": 0.03, "note": "Refrigerated retail"},
            {"stage": "Closed-loop recycling", "co2_share": 0.10, "note": "Back in 60 days avg."},
        ],
    },
    {
        "id": "bioplastic-pla-tray",
        "name": "Compostable PLA Produce Tray",
        "category": "Produce",
        "material": "PLA (corn-derived bioplastic)",
        "format": "250 g berry tray",
        "image": "https://images.pexels.com/photos/4393660/pexels-photo-4393660.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "co2_kg": 0.031,
        "baseline_co2_kg": 0.046,
        "water_l": 1.2,
        "energy_mj": 0.7,
        "recyclability_pct": 18,
        "shelf_life_days": 9,
        "cost_eur": 0.09,
        "weight_g": 8.0,
        "score_grade": "B",
        "score_value": 68,
        "highlights": [
            "Plant-based feedstock (corn starch)",
            "Industrially compostable (EN 13432)",
            "Limited home-compost access in EU"
        ],
        "lifecycle": [
            {"stage": "Corn cultivation", "co2_share": 0.30, "note": "Agricultural inputs"},
            {"stage": "PLA polymerisation", "co2_share": 0.25, "note": "Fermentation + lactide"},
            {"stage": "Thermoforming", "co2_share": 0.20, "note": "Lower heat than PP"},
            {"stage": "Chilled retail", "co2_share": 0.10, "note": "Short shelf-life window"},
            {"stage": "Industrial composting", "co2_share": 0.15, "note": "Requires dedicated facility"},
        ],
    },
    {
        "id": "sugarcane-clamshell",
        "name": "Bagasse Clamshell",
        "category": "Produce",
        "material": "Sugarcane bagasse pulp",
        "format": "500 ml salad box",
        "image": "https://images.unsplash.com/photo-1621448933873-d0cf2db2a7d1?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "co2_kg": 0.022,
        "baseline_co2_kg": 0.046,
        "water_l": 1.8,
        "energy_mj": 0.6,
        "recyclability_pct": 86,
        "shelf_life_days": 5,
        "cost_eur": 0.11,
        "weight_g": 11.0,
        "score_grade": "A",
        "score_value": 86,
        "highlights": [
            "Made from sugar milling residue",
            "Home & industrially compostable",
            "Plastic-free, microwave-safe"
        ],
        "lifecycle": [
            {"stage": "Bagasse collection", "co2_share": 0.15, "note": "Agricultural by-product"},
            {"stage": "Pulp moulding", "co2_share": 0.35, "note": "Hot press forming"},
            {"stage": "Transport (Asia→EU)", "co2_share": 0.30, "note": "Ocean freight dominant"},
            {"stage": "Chilled retail", "co2_share": 0.08, "note": "Short shelf-life"},
            {"stage": "Compost or organics bin", "co2_share": 0.12, "note": "Home-compost verified"},
        ],
    },
    {
        "id": "eps-meat-tray",
        "name": "Expanded Polystyrene Meat Tray",
        "category": "Meat & Fish",
        "material": "EPS #6 foam",
        "format": "400 g supermarket tray",
        "image": "https://images.unsplash.com/photo-1506617564039-2f3b650b7010?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "co2_kg": 0.049,
        "baseline_co2_kg": 0.042,
        "water_l": 0.7,
        "energy_mj": 1.3,
        "recyclability_pct": 7,
        "shelf_life_days": 5,
        "cost_eur": 0.04,
        "weight_g": 6.0,
        "score_grade": "E",
        "score_value": 24,
        "highlights": [
            "Almost no EU recycling infrastructure",
            "Fragments into persistent microplastics",
            "Banned in a growing list of EU regions"
        ],
        "lifecycle": [
            {"stage": "Styrene monomer", "co2_share": 0.50, "note": "Fossil-derived"},
            {"stage": "Foaming (pentane blowing)", "co2_share": 0.25, "note": "VOC emissions"},
            {"stage": "Cold-chain transport", "co2_share": 0.15, "note": "Meat refrigeration"},
            {"stage": "Use", "co2_share": 0.02, "note": "Negligible"},
            {"stage": "Landfill / incineration", "co2_share": 0.08, "note": "7% recovered"},
        ],
    },
    {
        "id": "steel-food-can",
        "name": "Tinplate Steel Food Can",
        "category": "Pantry",
        "material": "Steel + tin coating",
        "format": "400 g tomatoes",
        "image": "https://images.unsplash.com/photo-1583947581924-860bda3c9641?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "co2_kg": 0.13,
        "baseline_co2_kg": 0.16,
        "water_l": 1.6,
        "energy_mj": 2.0,
        "recyclability_pct": 82,
        "shelf_life_days": 1095,
        "cost_eur": 0.09,
        "weight_g": 58,
        "score_grade": "B",
        "score_value": 69,
        "highlights": [
            "Magnetic sorting = 82% recovery",
            "3-year ambient shelf life",
            "Prevents food waste at scale"
        ],
        "lifecycle": [
            {"stage": "Steel production", "co2_share": 0.55, "note": "BOF + 35% scrap"},
            {"stage": "Can forming", "co2_share": 0.15, "note": "Two-piece draw-wall-iron"},
            {"stage": "Filling & retort", "co2_share": 0.15, "note": "Heat sterilisation"},
            {"stage": "Ambient shelf", "co2_share": 0.05, "note": "No cold-chain"},
            {"stage": "Magnetic recycling", "co2_share": 0.10, "note": "Highest EU recovery rate"},
        ],
    },
    {
        "id": "stand-up-pouch",
        "name": "Multi-layer Stand-up Pouch",
        "category": "Snacks",
        "material": "PET/AL/PE laminate",
        "format": "200 g snack pouch",
        "image": "https://images.unsplash.com/photo-1627843240043-b3f1e0d1c0b6?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "co2_kg": 0.022,
        "baseline_co2_kg": 0.028,
        "water_l": 0.3,
        "energy_mj": 0.5,
        "recyclability_pct": 4,
        "shelf_life_days": 365,
        "cost_eur": 0.06,
        "weight_g": 4.5,
        "score_grade": "E",
        "score_value": 29,
        "highlights": [
            "Ultra-light — minimal transport CO₂",
            "12-month ambient shelf life",
            "Not recyclable: mixed polymers + foil"
        ],
        "lifecycle": [
            {"stage": "Multi-polymer resins", "co2_share": 0.45, "note": "3+ layers laminated"},
            {"stage": "Lamination", "co2_share": 0.25, "note": "Solvent-based bonding"},
            {"stage": "Filling & transport", "co2_share": 0.15, "note": "Flat-pack savings"},
            {"stage": "Ambient shelf", "co2_share": 0.05, "note": "Excellent barrier"},
            {"stage": "Incineration", "co2_share": 0.10, "note": "Not mechanically recyclable"},
        ],
    },
    {
        "id": "cardboard-egg-carton",
        "name": "Moulded Pulp Egg Carton",
        "category": "Dairy",
        "material": "Recycled paper pulp",
        "format": "10-pack egg carton",
        "image": "https://images.unsplash.com/photo-1506086679524-493c64fdfaa6?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "co2_kg": 0.018,
        "baseline_co2_kg": 0.035,
        "water_l": 1.1,
        "energy_mj": 0.4,
        "recyclability_pct": 92,
        "shelf_life_days": 28,
        "cost_eur": 0.06,
        "weight_g": 25,
        "score_grade": "A",
        "score_value": 90,
        "highlights": [
            "100% post-consumer paper fibre",
            "Kerbside recyclable + compostable",
            "Shock-absorbent, no plastic needed"
        ],
        "lifecycle": [
            {"stage": "Recycled pulp", "co2_share": 0.30, "note": "Old newspapers & board"},
            {"stage": "Wet moulding", "co2_share": 0.30, "note": "Heated drying ovens"},
            {"stage": "Transport", "co2_share": 0.15, "note": "Stacked dense pallets"},
            {"stage": "Retail shelf", "co2_share": 0.05, "note": "Short chilled window"},
            {"stage": "Paper recycling", "co2_share": 0.20, "note": "Accepted in all EU MRFs"},
        ],
    },
    {
        "id": "kraft-paper-wrap",
        "name": "Unbleached Kraft Sandwich Wrap",
        "category": "Bakery & Deli",
        "material": "Kraft paper + PLA coating",
        "format": "30x30 cm wrap",
        "image": "https://images.unsplash.com/photo-1584727638096-042c45049ebe?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "co2_kg": 0.012,
        "baseline_co2_kg": 0.021,
        "water_l": 0.8,
        "energy_mj": 0.3,
        "recyclability_pct": 65,
        "shelf_life_days": 2,
        "cost_eur": 0.03,
        "weight_g": 8.0,
        "score_grade": "A",
        "score_value": 84,
        "highlights": [
            "FSC-certified virgin kraft",
            "Grease-proof without PFAS",
            "Home-compostable in 90 days"
        ],
        "lifecycle": [
            {"stage": "FSC pulp", "co2_share": 0.30, "note": "Responsibly managed forests"},
            {"stage": "Paper making", "co2_share": 0.35, "note": "Biomass-powered mills"},
            {"stage": "PLA coating", "co2_share": 0.15, "note": "PFAS-free grease barrier"},
            {"stage": "Use", "co2_share": 0.05, "note": "Single-use, minutes-hours"},
            {"stage": "Compost or paper bin", "co2_share": 0.15, "note": "Dual end-of-life routes"},
        ],
    },
    {
        "id": "bamboo-fiber-bowl",
        "name": "Bamboo Fibre Takeaway Bowl",
        "category": "Food Service",
        "material": "Bamboo fibre composite",
        "format": "750 ml noodle bowl",
        "image": "https://images.unsplash.com/photo-1600713150048-6d5d1e48e2b7?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "co2_kg": 0.026,
        "baseline_co2_kg": 0.058,
        "water_l": 2.2,
        "energy_mj": 0.8,
        "recyclability_pct": 80,
        "shelf_life_days": 1,
        "cost_eur": 0.14,
        "weight_g": 18,
        "score_grade": "A",
        "score_value": 81,
        "highlights": [
            "Rapidly renewable bamboo (3-yr harvest)",
            "Microwave and freezer safe",
            "Home-compostable, PFAS-free"
        ],
        "lifecycle": [
            {"stage": "Bamboo cultivation", "co2_share": 0.20, "note": "Negative-emission crop"},
            {"stage": "Fibre moulding", "co2_share": 0.35, "note": "Heat + pressure"},
            {"stage": "Transport", "co2_share": 0.25, "note": "Primarily from Asia"},
            {"stage": "Single use", "co2_share": 0.05, "note": "Hot food service"},
            {"stage": "Compost", "co2_share": 0.15, "note": "90-day home compost"},
        ],
    },
    {
        "id": "glass-jam-jar",
        "name": "Glass Jam Jar",
        "category": "Pantry",
        "material": "Flint glass + steel lid",
        "format": "370 ml jar",
        "image": "https://images.unsplash.com/photo-1568926743817-dacfc0622181?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjY2NjV8MHwxfHNlYXJjaHwyfHxnbGFzcyUyMGphciUyMGZvb2R8ZW58MHx8fHwxNzc2Nzg4Njc4fDA&ixlib=rb-4.1.0&q=85",
        "co2_kg": 0.19,
        "baseline_co2_kg": 0.16,
        "water_l": 1.2,
        "energy_mj": 2.8,
        "recyclability_pct": 76,
        "shelf_life_days": 730,
        "cost_eur": 0.18,
        "weight_g": 195,
        "score_grade": "C",
        "score_value": 58,
        "highlights": [
            "Kerbside recyclable in all EU states",
            "Reusable at household level",
            "Heavy = higher transport CO₂"
        ],
        "lifecycle": [
            {"stage": "Sand & cullet", "co2_share": 0.22, "note": "~60% cullet input"},
            {"stage": "Melting", "co2_share": 0.40, "note": "Furnace 1500°C"},
            {"stage": "Transport (heavy)", "co2_share": 0.20, "note": "195 g per jar"},
            {"stage": "Pantry shelf", "co2_share": 0.03, "note": "2-year shelf life"},
            {"stage": "Glass recycling", "co2_share": 0.15, "note": "Infinite loop"},
        ],
    },
    {
        "id": "aluminium-coffee-capsule",
        "name": "Aluminium Coffee Capsule",
        "category": "Beverages",
        "material": "Aluminium + PE membrane",
        "format": "5.5 g single-serve",
        "image": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "co2_kg": 0.028,
        "baseline_co2_kg": 0.021,
        "water_l": 0.6,
        "energy_mj": 0.9,
        "recyclability_pct": 32,
        "shelf_life_days": 540,
        "cost_eur": 0.08,
        "weight_g": 3.0,
        "score_grade": "D",
        "score_value": 44,
        "highlights": [
            "Portion-controlled = less coffee wasted",
            "Recyclable but needs dedicated capsule stream",
            "High embodied CO₂ per cup"
        ],
        "lifecycle": [
            {"stage": "Aluminium foil", "co2_share": 0.55, "note": "Virgin + 40% scrap"},
            {"stage": "Capsule forming", "co2_share": 0.15, "note": "Deep-draw press"},
            {"stage": "Transport", "co2_share": 0.12, "note": "Compact but global"},
            {"stage": "Use (brewing)", "co2_share": 0.08, "note": "Machine heat"},
            {"stage": "Dedicated recycling", "co2_share": 0.10, "note": "Specialist take-back"},
        ],
    },
    {
        "id": "wine-glass-bottle",
        "name": "Green Glass Wine Bottle",
        "category": "Beverages",
        "material": "Recycled green glass",
        "format": "750 ml Bordeaux",
        "image": "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "co2_kg": 0.31,
        "baseline_co2_kg": 0.45,
        "water_l": 2.1,
        "energy_mj": 4.2,
        "recyclability_pct": 78,
        "shelf_life_days": 3650,
        "cost_eur": 0.42,
        "weight_g": 420,
        "score_grade": "C",
        "score_value": 60,
        "highlights": [
            "Mature EU glass collection (78%)",
            "Decade-plus shelf life",
            "Heavy — transport-heavy footprint"
        ],
        "lifecycle": [
            {"stage": "Cullet + silica", "co2_share": 0.28, "note": "~65% recycled content"},
            {"stage": "Furnace melt", "co2_share": 0.38, "note": "Natural-gas fired"},
            {"stage": "Long-haul transport", "co2_share": 0.22, "note": "Dense 420 g payload"},
            {"stage": "Cellar storage", "co2_share": 0.02, "note": "Ambient, decades"},
            {"stage": "Bottle bank", "co2_share": 0.10, "note": "Closed-loop recycling"},
        ],
    },
    {
        "id": "pla-cold-cup",
        "name": "PLA Cold-Drink Cup",
        "category": "Food Service",
        "material": "PLA #7 bioplastic",
        "format": "400 ml iced-coffee cup",
        "image": "https://images.unsplash.com/photo-1521986329282-0436c1f1e212?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "co2_kg": 0.019,
        "baseline_co2_kg": 0.028,
        "water_l": 1.1,
        "energy_mj": 0.5,
        "recyclability_pct": 12,
        "shelf_life_days": 1,
        "cost_eur": 0.07,
        "weight_g": 11.0,
        "score_grade": "C",
        "score_value": 56,
        "highlights": [
            "Plant-based clear polymer",
            "Industrially compostable (EN 13432)",
            "Contaminates PET recycling if misplaced"
        ],
        "lifecycle": [
            {"stage": "Corn cultivation", "co2_share": 0.30, "note": "Agricultural phase"},
            {"stage": "PLA resin", "co2_share": 0.25, "note": "Lactic acid fermentation"},
            {"stage": "Thermoforming", "co2_share": 0.20, "note": "Lower heat than PET"},
            {"stage": "Cold use", "co2_share": 0.05, "note": "No hot-drink safe"},
            {"stage": "Industrial compost", "co2_share": 0.20, "note": "Needs dedicated stream"},
        ],
    },
    {
        "id": "molded-pulp-tray",
        "name": "Moulded Pulp Produce Tray",
        "category": "Produce",
        "material": "Recycled paper pulp",
        "format": "500 g apple tray",
        "image": "https://images.unsplash.com/photo-1524593689594-aae2f26b75ab?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "co2_kg": 0.014,
        "baseline_co2_kg": 0.032,
        "water_l": 0.9,
        "energy_mj": 0.3,
        "recyclability_pct": 88,
        "shelf_life_days": 21,
        "cost_eur": 0.05,
        "weight_g": 18,
        "score_grade": "A",
        "score_value": 87,
        "highlights": [
            "100% post-consumer fibre",
            "Home-compostable + kerbside recyclable",
            "Cushions fruit without plastic mesh"
        ],
        "lifecycle": [
            {"stage": "Recycled pulp", "co2_share": 0.28, "note": "Old newspapers & board"},
            {"stage": "Wet moulding", "co2_share": 0.32, "note": "Heated drying"},
            {"stage": "Transport", "co2_share": 0.14, "note": "Nested pallet-dense"},
            {"stage": "Retail shelf", "co2_share": 0.06, "note": "Ambient to chilled"},
            {"stage": "Paper recycling", "co2_share": 0.20, "note": "All EU MRFs accept"},
        ],
    },
    {
        "id": "rigid-cardboard-box",
        "name": "Corrugated Cardboard Shipper",
        "category": "Food Service",
        "material": "Recycled corrugated board",
        "format": "Medium e-commerce box",
        "image": "https://images.unsplash.com/photo-1607344645866-009c320b63e0?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "co2_kg": 0.12,
        "baseline_co2_kg": 0.22,
        "water_l": 2.8,
        "energy_mj": 1.2,
        "recyclability_pct": 93,
        "shelf_life_days": 3,
        "cost_eur": 0.22,
        "weight_g": 140,
        "score_grade": "A",
        "score_value": 82,
        "highlights": [
            "93% EU-wide recycling rate",
            "80%+ recycled fibre typical",
            "FSC-certified when labelled"
        ],
        "lifecycle": [
            {"stage": "Recycled kraftliner", "co2_share": 0.35, "note": "Old corrugated containers"},
            {"stage": "Corrugating", "co2_share": 0.25, "note": "Steam + adhesive"},
            {"stage": "Transit", "co2_share": 0.20, "note": "Flat-packed shipment"},
            {"stage": "Single use", "co2_share": 0.05, "note": "Typically 1 trip"},
            {"stage": "Paper recycling", "co2_share": 0.15, "note": "Blue-bin kerbside"},
        ],
    },
    {
        "id": "hdpe-milk-jug",
        "name": "HDPE Fresh-Milk Jug",
        "category": "Dairy",
        "material": "HDPE #2",
        "format": "2 L jug",
        "image": "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "co2_kg": 0.11,
        "baseline_co2_kg": 0.13,
        "water_l": 1.0,
        "energy_mj": 2.4,
        "recyclability_pct": 51,
        "shelf_life_days": 12,
        "cost_eur": 0.07,
        "weight_g": 42,
        "score_grade": "C",
        "score_value": 62,
        "highlights": [
            "Widely accepted HDPE #2 stream",
            "Impact-resistant at low temps",
            "Virgin fossil feedstock"
        ],
        "lifecycle": [
            {"stage": "HDPE resin", "co2_share": 0.58, "note": "Fossil naphtha"},
            {"stage": "Blow moulding", "co2_share": 0.18, "note": "Extrusion blow"},
            {"stage": "Cold-chain transport", "co2_share": 0.12, "note": "4°C logistics"},
            {"stage": "Home storage", "co2_share": 0.02, "note": "Fridge"},
            {"stage": "Bottle recycling", "co2_share": 0.10, "note": "Bale → flake → pellet"},
        ],
    },
    {
        "id": "paper-straw",
        "name": "Unbleached Paper Straw",
        "category": "Food Service",
        "material": "FSC paper, triple-ply",
        "format": "197 mm straw",
        "image": "https://images.unsplash.com/photo-1597318374671-6ce1e1e14f96?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "co2_kg": 0.003,
        "baseline_co2_kg": 0.005,
        "water_l": 0.15,
        "energy_mj": 0.08,
        "recyclability_pct": 60,
        "shelf_life_days": 730,
        "cost_eur": 0.01,
        "weight_g": 0.6,
        "score_grade": "B",
        "score_value": 72,
        "highlights": [
            "PFAS-free food contact",
            "Home-compostable (90 days)",
            "Softens after ~45 min in cold drink"
        ],
        "lifecycle": [
            {"stage": "FSC paper", "co2_share": 0.40, "note": "Virgin fibre + additives"},
            {"stage": "Spiral winding", "co2_share": 0.25, "note": "Food-safe adhesives"},
            {"stage": "Transport", "co2_share": 0.15, "note": "Dense bundles"},
            {"stage": "Use", "co2_share": 0.05, "note": "Minutes of contact"},
            {"stage": "Compost / paper bin", "co2_share": 0.15, "note": "Dual route"},
        ],
    },
    {
        "id": "mushroom-packaging",
        "name": "Mycelium Protective Packaging",
        "category": "Food Service",
        "material": "Mycelium + agricultural waste",
        "format": "Fitted produce cushion",
        "image": "https://images.unsplash.com/photo-1586201375761-83865001e31c?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "co2_kg": 0.009,
        "baseline_co2_kg": 0.045,
        "water_l": 0.9,
        "energy_mj": 0.3,
        "recyclability_pct": 100,
        "shelf_life_days": 60,
        "cost_eur": 0.19,
        "weight_g": 35,
        "score_grade": "A",
        "score_value": 92,
        "highlights": [
            "Grown, not manufactured — biodegrades in 30 days",
            "Replaces EPS with similar cushioning",
            "Home-compostable, water-soluble"
        ],
        "lifecycle": [
            {"stage": "Agri-waste substrate", "co2_share": 0.15, "note": "Hemp hurds + straw"},
            {"stage": "Mycelium growth", "co2_share": 0.35, "note": "7-day room-temp incubation"},
            {"stage": "Heat-kill & dry", "co2_share": 0.25, "note": "Stops growth"},
            {"stage": "Transport", "co2_share": 0.15, "note": "Lightweight, void-fill"},
            {"stage": "Compost", "co2_share": 0.10, "note": "30-day home compost"},
        ],
    },
    {
        "id": "pet-salad-clamshell",
        "name": "PET Salad Clamshell",
        "category": "Produce",
        "material": "PET #1 (virgin)",
        "format": "200 g leafy-green pack",
        "image": "https://images.unsplash.com/photo-1540420828642-fca2c5c18abe?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "co2_kg": 0.058,
        "baseline_co2_kg": 0.046,
        "water_l": 2.1,
        "energy_mj": 1.3,
        "recyclability_pct": 42,
        "shelf_life_days": 7,
        "cost_eur": 0.08,
        "weight_g": 22,
        "score_grade": "D",
        "score_value": 48,
        "highlights": [
            "Crystal-clear shelf visibility",
            "Lower EU recycling than PET bottles",
            "Modified-atmosphere compatible"
        ],
        "lifecycle": [
            {"stage": "Virgin PET resin", "co2_share": 0.55, "note": "Fossil-derived"},
            {"stage": "Thermoforming", "co2_share": 0.18, "note": "Clamshell mould"},
            {"stage": "Chilled transport", "co2_share": 0.15, "note": "4°C supply chain"},
            {"stage": "Retail shelf", "co2_share": 0.04, "note": "Under 10 days"},
            {"stage": "Mixed-plastics bin", "co2_share": 0.08, "note": "42% actually recycled"},
        ],
    },
    {
        "id": "reusable-steel-bottle",
        "name": "Reusable Steel Bottle",
        "category": "Beverages",
        "material": "Food-grade stainless 304",
        "format": "500 ml vacuum bottle",
        "image": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "co2_kg": 0.015,
        "baseline_co2_kg": 0.083,
        "water_l": 0.4,
        "energy_mj": 0.6,
        "recyclability_pct": 88,
        "shelf_life_days": 1825,
        "cost_eur": 12.5,
        "weight_g": 260,
        "score_grade": "A",
        "score_value": 91,
        "highlights": [
            "Amortised over ~1 000 uses",
            "Inert, no microplastic leaching",
            "Steel recycles at 88% in EU"
        ],
        "lifecycle": [
            {"stage": "Stainless steel", "co2_share": 0.45, "note": "Per-use share only"},
            {"stage": "Forming + polishing", "co2_share": 0.20, "note": "One-time impact"},
            {"stage": "Transport", "co2_share": 0.10, "note": "Distributed over lifetime"},
            {"stage": "Daily use + washing", "co2_share": 0.15, "note": "Hot tap water"},
            {"stage": "Scrap recycling", "co2_share": 0.10, "note": "Closed-loop metal"},
        ],
    },
]


def get_all():
    return PACKAGINGS


def get_by_id(pid: str):
    for p in PACKAGINGS:
        if p["id"] == pid:
            return p
    return None


def categories():
    return sorted({p["category"] for p in PACKAGINGS})
